language: go

go:
  - 1.13.x

services:
  - redis-server

script:
  - go test ./pkg/algorithm/...
  - go test ./pkg/encrypt/...
  - go test ./pkg/golang/...
  - go test ./pkg/jwt/...
  - go test ./pkg/patterns/...
  - go test ./pkg/redigo/...
  - go test ./pkg/redis/...
  - go test ./pkg/util/...

before_install:
  - go get -v -t -d ./...

