language: go

go:
  - 1.13.x

script:
  - go version

jobs:
  include:
    - stage: test algorithm
      script: cd pkg/algorithm && go test ./...
    - stage: test encrypt
      script: cd pkg/encrypt && go test .
    - stage: test golang
      script: cd pkg/golang && go test ./...
    - stage: test jwt
      script: cd pkg/jwt && go test .
    - stage: test patterns
      script: cd pkg/patterns && go test ./...
    - stage: test util
      script: cd pkg/util && go test .

