package rabbitmq

import "fmt"

func TopicQueueBind(exchangeName, queueName, topicName string) {
	NewRabbitmq()
	ch, err := rabbitmqClient.Channel()
	if err != nil {
		panic(err)
	}
	defer ch.Close()

	// In the amqp client, when we supply queue name as an empty string
	queue, err := ch.QueueDeclare(
		queueName, // name
		true,      // durable
		false,     // delete when unused
		false,     // exclusive
		false,     // no-wait
		nil,       // arguments
	)
	// the queue instance contains a random queue name generated by RabbitMQ. For example it may look like amq.gen-JzTY20BRgKO-HjmUJj0wLg.
	if err != nil {
		panic(err)
	}
	fmt.Println(queue.Name)
	err = ch.QueueBind(
		queue.Name,   // queue name
		topicName,    // routing key
		exchangeName, // exchange
		false,
		nil)
	if err != nil {
		panic(err)
	}
}
